//Naming Conventions: MP=Main Page, IP=Inventory Page, FP=Fight Page, But=Button, Img=Image, 
const IPtoMPBut = document.getElementById(''),
      MPtoIPBut = document.getElementById(''),
      MPtoFPBut = document.getElementById(''),
      FPtoMPBut = document.getElementById(''),
      = document.getElementById(''),
      = document.getElementById(''),
      = document.getElementById(''),
      = document.getElementById(''),
      = document.getElementById(''),
      = document.getElementById(''),
      = document.getElementById(''),
      = document.getElementById(''),
